/**
 * Year 6 English, following the national curriculum in England (2014):
 * - English Appendix 1 (Spelling): the Years 5 and 6 statutory word list,
 *   spelling rules and homophones.
 * - English Appendix 2 (Vocabulary, grammar and punctuation): Year 6 content.
 * Grammar terms follow the curriculum glossary (e.g. what counts as passive).
 *
 * Spelling levels are this app's judgement of difficulty, not official
 * groupings. Misspellings were chosen so none is a correct spelling in
 * British or American English.
 */
import type { Level, Question } from '../brain/types';
import { pickFromBank, rowsToQuestions, type Row } from './bank';
import { classifySpelling } from './bugs';
import { readingQuestions } from './reading';

/** [level, correct spelling, two misspellings, optional memory tip]. */
type SpellingRow = [Level, string, [string, string], string?];

/** Statutory word list for Years 5 and 6 (English Appendix 1). */
export const SPELLING_WORDS: SpellingRow[] = [
  [1, 'average', ['averige', 'avrage']],
  [1, 'bargain', ['bargin', 'bargian'], 'It ends in -gain: bar + gain.'],
  [1, 'bruise', ['bruse', 'bruize'], 'There is a silent "i" after the "u".'],
  [1, 'develop', ['develope', 'devlop'], 'No "e" on the end.'],
  [1, 'forty', ['fourty', 'fortey'], 'Four has a "u" but forty does not.'],
  [1, 'identity', ['identaty', 'idenity']],
  [1, 'language', ['langauge', 'languige'], 'The "u" comes straight after the "g": lang-u-age.'],
  [1, 'muscle', ['mussle', 'muscel'], 'It has a silent "c": mus-cle.'],
  [1, 'relevant', ['relevent', 'relavant'], 'It ends in -ant.'],
  [1, 'shoulder', ['sholder', 'shouldor'], 'It starts like "should".'],
  [1, 'soldier', ['soldeir', 'soljer'], 'The "j" sound is spelt "di": sol-di-er.'],
  [1, 'stomach', ['stomache', 'stumach'], 'The "k" sound is spelt "ch" and there is no "e" on the end.'],
  [1, 'suggest', ['sugest', 'suggust'], 'Double "g".'],
  [1, 'symbol', ['symbal', 'simbol'], 'It uses "y" and ends in -bol.'],
  [1, 'system', ['sistem', 'systom'], 'It uses "y": sys-tem.'],
  [1, 'variety', ['varity', 'variaty'], 'Think of "vary": var-i-e-ty.'],
  [1, 'vegetable', ['vegtable', 'vegetible'], 'Say it slowly: veg-e-ta-ble.'],
  [1, 'yacht', ['yatch', 'yaht'], 'The "ch" is silent and comes after the "a": ya-ch-t.'],
  [2, 'achieve', ['acheive', 'achive'], '"i" before "e" in achieve.'],
  [2, 'amateur', ['amature', 'amatuer'], 'It ends in -eur, like "chauffeur".'],
  [2, 'ancient', ['anceint', 'ancint'], 'The "sh" sound is spelt "ci": an-ci-ent.'],
  [2, 'attached', ['attatched', 'atached'], 'Double "t", then -ached.'],
  [2, 'available', ['availible', 'avaliable'], 'avail + able.'],
  [2, 'awkward', ['awkard', 'awkword'], 'awk + ward.'],
  [2, 'category', ['catagory', 'categary'], 'cat-e-gory.'],
  [2, 'community', ['comunity', 'communitty'], 'Double "m", single "t".'],
  [2, 'competition', ['competision', 'compitition'], 'Think of "compete": compet-ition.'],
  [2, 'dictionary', ['dictionery', 'dictionairy'], 'diction + ary.'],
  [2, 'excellent', ['excelent', 'exellent'], 'It has "exc" and double "l".'],
  [2, 'familiar', ['familar', 'familier'], 'Think of "family": famil-i-ar.'],
  [2, 'foreign', ['foriegn', 'forein'], 'It has "ei" and a silent "g": for-eig-n.'],
  [2, 'frequently', ['frequantly', 'freqently'], 'frequent + ly.'],
  [2, 'government', ['goverment', 'govenment'], 'govern + ment: don\'t forget the "n".'],
  [2, 'interfere', ['interfear', 'interfer'], 'inter + fere.'],
  [2, 'occupy', ['ocupy', 'occuppy'], 'Double "c", single "p".'],
  [2, 'persuade', ['pursuade', 'persuaid'], 'It starts with "per".'],
  [2, 'physical', ['phisical', 'physicle'], 'The "f" sound is "ph" and it uses "y".'],
  [2, 'signature', ['signiture', 'signatuer'], 'Think of "sign": sign-a-ture.'],
  [2, 'temperature', ['temprature', 'temperture'], 'Say every part: tem-per-a-ture.'],
  [2, 'vehicle', ['vehical', 'veicle'], 'It has a silent "h" and ends in -icle.'],
  [3, 'accompany', ['acompany', 'accompeny'], 'Double "c": ac + company.'],
  [3, 'according', ['acording', 'accourding'], 'Double "c": ac + cord + ing.'],
  [3, 'apparent', ['apparant', 'aparent'], 'Double "p", and it ends in -ent.'],
  [3, 'appreciate', ['apreciate', 'appreshiate'], 'Double "p", and the "sh" sound is spelt "ci".'],
  [3, 'communicate', ['comunicate', 'communecate'], 'Double "m".'],
  [3, 'correspond', ['corespond', 'correspund'], 'Double "r": cor + respond.'],
  [3, 'criticise', ['critisise', 'critticise'], 'critic + ise.'],
  [3, 'curiosity', ['curiousity', 'curiosaty'], 'The "u" from "curious" is dropped.'],
  [3, 'definite', ['definate', 'definit'], 'There is "finite" inside definite.'],
  [3, 'desperate', ['desparate', 'desprate'], 'des-per-ate.'],
  [3, 'determined', ['determind', 'determened'], 'determine + d.'],
  [3, 'environment', ['enviroment', 'environmant'], 'There is "iron" in the middle: env-iron-ment.'],
  [3, 'equipment', ['equiptment', 'equippment'], 'equip + ment: no "t" before -ment and only one "p".'],
  [3, 'explanation', ['explaination', 'explanasion'], 'Unlike "explain", there is no "i" after the "a".'],
  [3, 'individual', ['individule', 'indivdual'], 'in-di-vid-u-al.'],
  [3, 'leisure', ['liesure', 'leasure'], 'It has "ei", and the "s" sounds like the "s" in "treasure".'],
  [3, 'lightning', ['litening', 'lightnig'], 'Lightning in a storm has no "e". ("Lightening" means making lighter.)'],
  [3, 'neighbour', ['nieghbour', 'neighbur'], 'It starts with "neigh", like a horse.'],
  [3, 'profession', ['proffession', 'profesion'], 'One "f", double "s".'],
  [3, 'programme', ['programe', 'progamme'], 'In British English a TV programme has "mme" at the end.'],
  [3, 'recognise', ['reconise', 'recognice'], 'There is a "g" in the middle: re-cog-nise.'],
  [3, 'sacrifice', ['sacrafice', 'sacrifise'], 'sac-ri-fice.'],
  [3, 'secretary', ['secretery', 'secertary'], 'There is a "secret" in secretary.'],
  [3, 'sincerely', ['sincerly', 'sincerley'], 'sincere + ly: keep the "e".'],
  [3, 'sufficient', ['sufficiant', 'suficient'], 'Double "f" and it ends in -cient.'],
  [3, 'twelfth', ['twelth', 'twelveth'], 'Don\'t forget the "f": twel-f-th.'],
  [4, 'aggressive', ['agressive', 'aggresive'], 'Double "g" and double "s".'],
  [4, 'cemetery', ['cemetary', 'cemitery'], 'Three "e"s: c-e-m-e-t-e-ry.'],
  [4, 'committee', ['commitee', 'comittee'], 'Double "m", double "t", double "e".'],
  [4, 'conscious', ['concious', 'consious'], 'It contains "sc" and "ci": con-sc-ious.'],
  [4, 'convenience', ['conveniance', 'convienience'], 'con-ven-i-ence.'],
  [4, 'disastrous', ['disasterous', 'disastrus'], 'The "e" from "disaster" is dropped.'],
  [4, 'equipped', ['equiped', 'eqipped'], 'Double the "p" before -ed.'],
  [4, 'especially', ['especialy', 'expecially'], 'especial + ly.'],
  [4, 'existence', ['existance', 'existense'], 'It ends in -ence.'],
  [4, 'guarantee', ['garantee', 'guarentee'], 'There is a silent "u" after the "g".'],
  [4, 'immediately', ['immediatly', 'imediately'], 'Double "m", and immediate + ly keeps the "e".'],
  [4, 'interrupt', ['interupt', 'interrubt'], 'Double "r": inter + rupt.'],
  [4, 'marvellous', ['marvellus', 'marvelouse'], 'In British English it has double "l" and ends in -ous.'],
  [4, 'nuisance', ['nuisence', 'nusance'], 'nui-sance.'],
  [4, 'occur', ['ocur', 'occurr'], 'Double "c", single "r".'],
  [4, 'opportunity', ['oppertunity', 'oportunity'], 'Double "p", and "port" is inside it.'],
  [4, 'parliament', ['parliment', 'parlament'], 'There is an "ia" in the middle: parl-ia-ment.'],
  [4, 'queue', ['queu', 'qeue'], 'Say the letters: q-u-e-u-e.'],
  [4, 'recommend', ['reccomend', 'recomend'], 'One "c", double "m".'],
  [4, 'restaurant', ['restaraunt', 'resturant'], 'rest-au-rant.'],
  [4, 'rhyme', ['ryhme', 'rhime'], 'It starts with "rh" and uses "y".'],
  [4, 'thorough', ['thurough', 'thourough'], 'It ends in -ough, like "borough".'],
  [5, 'accommodate', ['acommodate', 'accomodate'], 'It is big enough to accommodate double "c" and double "m".'],
  [5, 'conscience', ['concience', 'consciense'], 'con + science.'],
  [5, 'controversy', ['controvercy', 'contraversy'], 'contro-versy.'],
  [5, 'embarrass', ['embarass', 'embarras'], 'Double "r" and double "s".'],
  [5, 'exaggerate', ['exagerate', 'exaggarate'], 'Double "g": ex-ag-ger-ate.'],
  [5, 'harass', ['harrass', 'harras'], 'Single "r", double "s".'],
  [5, 'hindrance', ['hindrence', 'hindranse'], 'The "e" from "hinder" is dropped.'],
  [5, 'mischievous', ['mischievious', 'mischevous'], 'mischief + ous: no extra "i" before -ous.'],
  [5, 'necessary', ['neccessary', 'necesary'], 'One collar (c), two sleeves (ss).'],
  [5, 'prejudice', ['predjudice', 'prejudise'], 'pre-ju-dice: no "d" before the "j".'],
  [5, 'privilege', ['privelege', 'priviledge'], 'priv-i-lege: no "d".'],
  [5, 'pronunciation', ['pronounciation', 'pronunciasion'], 'Unlike "pronounce", there is no "o" after the first "n".'],
  [5, 'rhythm', ['rythm', 'rhythem'], 'Rhythm Helps Your Two Hips Move.'],
];

function spellingQuestions(): Question[] {
  return SPELLING_WORDS.map(([level, word, wrong, tip]) => ({
    skillId: 'spelling-words',
    level,
    id: `spelling-words#${word}`,
    prompt: 'Which spelling is correct?',
    answer: word,
    choices: [word, ...wrong],
    bugs: wrong.map((w): [string, string] => [classifySpelling(word, w), w]),
    explanation: tip ? `${word}: ${tip}` : `The correct spelling is ${word}.`,
  }));
}

/** Rules and example words from English Appendix 1, Years 5 and 6. */
const PATTERNS: Row[] = [
  [1, 'Which is the correct spelling?', 'receive', ['recieve'], 'After "c", the "ee" sound is spelt "ei": receive, deceive, ceiling.'],
  [1, 'Which is the correct spelling?', 'ceiling', ['cieling'], 'After "c", the "ee" sound is spelt "ei".'],
  [1, 'Which is the correct spelling?', 'deceive', ['decieve'], 'After "c", the "ee" sound is spelt "ei".'],
  [1, 'Which is the correct spelling?', 'perceive', ['percieve'], 'After "c", the "ee" sound is spelt "ei".'],
  [1, 'Which is the correct spelling?', 'seize', ['sieze'], 'Seize is an exception: it has "ei" even without a "c" before it.'],
  [1, 'Which is the correct spelling?', 'doubt', ['dout'], 'Doubt has a silent "b".'],
  [1, 'Which is the correct spelling?', 'island', ['iland'], 'Island has a silent "s".'],
  [1, 'Which is the correct spelling?', 'solemn', ['solem'], 'Solemn has a silent "n", like autumn.'],
  [2, 'Which is the correct spelling?', 'vicious', ['vitious'], 'The root word "vice" ends in -ce, so it takes -cious.'],
  [2, 'Which is the correct spelling?', 'gracious', ['gratious'], 'The root word "grace" ends in -ce, so it takes -cious.'],
  [2, 'Which is the correct spelling?', 'spacious', ['spatious'], 'The root word "space" ends in -ce, so it takes -cious.'],
  [2, 'Which is the correct spelling?', 'delicious', ['delitious'], 'Delicious ends in -cious.'],
  [2, 'Which is the correct spelling?', 'suspicious', ['suspitious'], 'Think of "suspicion": suspicious ends in -cious.'],
  [2, 'Which is the correct spelling?', 'ambitious', ['ambicious'], 'Think of "ambition": ambitious ends in -tious.'],
  [2, 'Which is the correct spelling?', 'cautious', ['caucious'], 'Think of "caution": cautious ends in -tious.'],
  [2, 'Which is the correct spelling?', 'nutritious', ['nutricious'], 'Think of "nutrition": nutritious ends in -tious.'],
  [2, 'Which is the correct spelling?', 'anxious', ['anxcious'], 'Anxious is an exception: it ends in -xious.'],
  [3, 'Which is the correct spelling?', 'official', ['offitial'], '-cial is common after a vowel letter (offi-cial).'],
  [3, 'Which is the correct spelling?', 'special', ['spetial'], '-cial is common after a vowel letter (spe-cial).'],
  [3, 'Which is the correct spelling?', 'artificial', ['artifitial'], '-cial is common after a vowel letter.'],
  [3, 'Which is the correct spelling?', 'partial', ['parcial'], '-tial is common after a consonant letter (par-tial).'],
  [3, 'Which is the correct spelling?', 'essential', ['essencial'], '-tial is common after a consonant letter (essen-tial).'],
  [3, 'Which is the correct spelling?', 'confidential', ['confidencial'], '-tial is common after a consonant letter (confiden-tial).'],
  [3, 'Which is the correct spelling?', 'initial', ['inicial'], 'Initial is an exception: -tial after a vowel.'],
  [3, 'Which is the correct spelling?', 'financial', ['finantial'], 'Financial is an exception: think of "finance".'],
  [4, 'Which is the correct spelling?', 'changeable', ['changable'], 'Keep the "e" after "g" so it still sounds soft: change + able.'],
  [4, 'Which is the correct spelling?', 'noticeable', ['noticable'], 'Keep the "e" after "c" so it still sounds soft: notice + able.'],
  [4, 'Which is the correct spelling?', 'dependable', ['dependible'], 'You can hear the whole root word "depend", so use -able.'],
  [4, 'Which is the correct spelling?', 'reliable', ['relyable'], 'rely + able: the "y" changes to "i".'],
  [4, 'Which is the correct spelling?', 'considerable', ['considerible'], 'There is a related word "consideration", so use -able.'],
  [4, 'Which is the correct spelling?', 'possible', ['possable'], 'You can\'t hear a complete root word before the ending, so use -ible.'],
  [4, 'Which is the correct spelling?', 'horrible', ['horrable'], 'You can\'t hear a complete root word before the ending, so use -ible.'],
  [4, 'Which is the correct spelling?', 'visible', ['visable'], 'You can\'t hear a complete root word before the ending, so use -ible.'],
  [4, 'Which is the correct spelling?', 'incredibly', ['incredably'], 'incredible → incredibly.'],
  [5, 'Which is the correct spelling?', 'observant', ['observent'], 'There is a related word "observation", so use -ant.'],
  [5, 'Which is the correct spelling?', 'hesitant', ['hesitent'], 'There is a related word "hesitation", so use -ant.'],
  [5, 'Which is the correct spelling?', 'tolerance', ['tolerence'], 'There is a related word "toleration", so use -ance.'],
  [5, 'Which is the correct spelling?', 'innocent', ['innocant'], 'After a soft "c" (an "s" sound), use -ent.'],
  [5, 'Which is the correct spelling?', 'frequency', ['frequancy'], 'After "qu", use -ency.'],
  [5, 'Which is the correct spelling?', 'confidence', ['confidance'], 'There is a related word "confidential" with a clear "e" sound, so use -ence.'],
  [5, 'Which is the correct spelling?', 'referring', ['refering'], 'The "fer" is still stressed (re-FER-ring), so double the "r".'],
  [5, 'Which is the correct spelling?', 'preferred', ['prefered'], 'The "fer" is still stressed (pre-FERRED), so double the "r".'],
  [5, 'Which is the correct spelling?', 'reference', ['referrence'], 'The "fer" is no longer stressed (REF-er-ence), so don\'t double the "r".'],
  [5, 'Which is the correct spelling?', 'preference', ['preferrence'], 'The "fer" is no longer stressed (PREF-er-ence), so don\'t double the "r".'],
];

/** Homophones and often-confused words from English Appendix 1, Years 5 and 6. */
const HOMOPHONES: Row[] = [
  [1, 'Read the poem ___ to the class.', 'aloud', ['allowed'], 'Aloud means out loud. Allowed means permitted.'],
  [1, 'Dogs are not ___ in the shop.', 'allowed', ['aloud'], 'Allowed means permitted. Aloud means out loud.'],
  [1, 'A ___ of cows crossed the road.', 'herd', ['heard'], 'A herd is a group of animals. Heard is the past tense of hear.'],
  [1, 'I ___ a strange noise outside.', 'heard', ['herd'], 'Heard is the past tense of hear.'],
  [1, 'Camels can survive in the hot ___.', 'desert', ['dessert'], 'A desert is a dry place. Dessert (with two s\'s, like "sweet stuff") is pudding.'],
  [1, 'We had ice cream for ___.', 'dessert', ['desert'], 'Dessert is the sweet course. Remember: dessert has two s\'s, like "sweet stuff".'],
  [1, 'The bridge is made of ___.', 'steel', ['steal'], 'Steel is a metal. Steal means to take something that isn\'t yours.'],
  [2, '___ coat is this?', 'Whose', ["Who's"], 'Whose means "belonging to whom". Who\'s is short for "who is" or "who has".'],
  [2, '___ coming to the party?', "Who's", ['Whose'], 'Who\'s is short for "who is": Who is coming to the party?'],
  [2, 'We had a ___ for dinner.', 'guest', ['guessed'], 'A guest is a visitor. Guessed is the past tense of guess.'],
  [2, 'She ___ the team to victory last year.', 'led', ['lead'], 'Led is the past tense of the verb "lead".'],
  [2, 'Old water pipes were sometimes made of ___.', 'lead', ['led'], 'Lead (rhymes with "bed") is also a heavy metal.'],
  [2, 'I ___ my friend in the corridor.', 'passed', ['past'], 'Passed is the past tense of the verb "pass".'],
  [2, 'He walked ___ the shop without stopping.', 'past', ['passed'], 'Past here shows place: he went by the shop.'],
  [2, 'They sailed to a small ___ off the coast.', 'isle', ['aisle'], 'An isle is an island. An aisle is a gangway between seats.'],
  [3, 'I ___ the piano every day.', 'practise', ['practice'], 'In British English, practise (with s) is the verb.'],
  [3, 'Football ___ is on Tuesday.', 'practice', ['practise'], 'In British English, practice (with c) is the noun.'],
  [3, 'Can I give you some ___?', 'advice', ['advise'], 'Advice (with c) is the noun.'],
  [3, 'I ___ you to wear a coat.', 'advise', ['advice'], 'Advise (with s, said with a "z" sound) is the verb.'],
  [3, 'We need to ___ a clever plan.', 'devise', ['device'], 'Devise (with s) is the verb, meaning to invent or plan.'],
  [3, 'A calculator is a useful ___.', 'device', ['devise'], 'Device (with c) is the noun.'],
  [3, 'Close the window, there\'s a cold ___.', 'draught', ['draft'], 'A draught is a current of air.'],
  [3, 'This is only my first ___ of the story.', 'draft', ['draught'], 'A draft is a first attempt at writing something.'],
  [3, 'The car was ___ at the traffic lights.', 'stationary', ['stationery'], 'Stationary means not moving. Stationery (e for envelopes) is paper, pens and so on.'],
  [3, 'Pens, paper and envelopes are called ___.', 'stationery', ['stationary'], 'Stationery: remember "e for envelopes".'],
  [3, 'After the long walk we felt ___.', 'weary', ['wary'], 'Weary means tired. Wary means cautious.'],
  [3, 'Be ___ of strangers you meet online.', 'wary', ['weary'], 'Wary means cautious. Weary means tired.'],
  [4, 'The cold weather may ___ our plans.', 'affect', ['effect'], 'Affect is usually a verb. Effect is usually a noun.'],
  [4, 'The medicine had a good ___.', 'effect', ['affect'], 'Effect is usually a noun: an effect.'],
  [4, 'Honesty is an important ___.', 'principle', ['principal'], 'A principle is a basic truth or belief.'],
  [4, 'The ___ of the college gave a speech.', 'principal', ['principle'], 'A principal is the most important person, such as the head of a college.'],
  [4, 'She paid me a lovely ___ about my drawing.', 'compliment', ['complement'], 'A compliment is a nice remark.'],
  [4, 'The red scarf is the perfect ___ to her coat.', 'complement', ['compliment'], 'A complement completes something (think "complete").'],
  [4, 'My uncle has a driving ___.', 'licence', ['license'], 'In British English, licence (with c) is the noun.'],
  [4, 'The council will ___ the café to sell food.', 'license', ['licence'], 'In British English, license (with s) is the verb.'],
  [4, 'Please ___ to the exit.', 'proceed', ['precede'], 'Proceed means go on. Precede means go before.'],
  [4, 'A short film will ___ the main film.', 'precede', ['proceed'], 'Precede means go in front of or before.'],
  [4, 'The shop made a ___ of £50.', 'profit', ['prophet'], 'Profit is money made from selling things. A prophet foretells the future.'],
  [5, 'The climbers began their ___ of the mountain.', 'ascent', ['assent'], 'Ascent means going up. Assent means agreement.'],
  [5, 'The head teacher gave her ___ to the plan.', 'assent', ['ascent'], 'Assent means agreement.'],
  [5, 'The plane began its ___ into London.', 'descent', ['dissent'], 'Descent means going down. Dissent means disagreement.'],
  [5, 'There was ___ among the players about the new rules.', 'dissent', ['descent'], 'Dissent means disagreement.'],
  [5, 'The rider fitted the ___ onto the horse.', 'bridle', ['bridal'], 'A bridle is the straps used to control a horse. Bridal is to do with a bride.'],
  [5, 'The ___ shop sells wedding dresses.', 'bridal', ['bridle'], 'Bridal means to do with a bride.'],
  [5, 'We need to ___ the length of these trousers.', 'alter', ['altar'], 'Alter means to change. An altar is a table in a church.'],
  [5, 'The wizard made a ___ about the future king.', 'prophecy', ['prophesy'], 'Prophecy (with c) is the noun.'],
  [5, 'The old woman claimed she could ___ the future.', 'prophesy', ['prophecy'], 'Prophesy (with s) is the verb.'],
];

/** Year 6 grammar (English Appendix 2 and its glossary). */
const GRAMMAR: Row[] = [
  [1, 'Which word is a synonym for "talk"?', 'speak', ['run', 'sleep', 'laugh'], 'Synonyms have the same or similar meanings: talk and speak.'],
  [1, 'Which word is a synonym for "old"?', 'elderly', ['young', 'new', 'tall'], 'Old and elderly have similar meanings, so they are synonyms.'],
  [1, 'Which word is a synonym for "begin"?', 'start', ['finish', 'stop', 'end'], 'Begin and start mean the same thing.'],
  [1, 'Which word is an antonym of "ancient"?', 'modern', ['old', 'historic', 'antique'], 'Antonyms have opposite meanings: ancient and modern.'],
  [1, 'Which word is an antonym of "generous"?', 'selfish', ['kind', 'giving', 'helpful'], 'Generous and selfish are opposites, so they are antonyms.'],
  [2, 'Which is the most formal way to say "find out"?', 'discover', ['check out', 'suss out', 'get'], 'In formal writing, "discover" replaces "find out".'],
  [2, 'Which is the most formal way to say "ask for"?', 'request', ['go for', 'beg', 'shout for'], 'In formal writing, "request" replaces "ask for".'],
  [2, 'Which is the most formal way to say "go in"?', 'enter', ['pop in', 'get in', 'nip in'], 'In formal writing, "enter" replaces "go in".'],
  [2, 'Which is the most formal way to say "help"?', 'assist', ['give a hand', 'sort out', 'back up'], 'In formal writing, "assist" replaces "help".'],
  [2, 'Which sentence is the most formal?', 'Pupils are requested to arrive by 9 a.m.', ['Get here by 9, OK?', 'Don\'t be late, guys!', 'Try and be in for 9.'], 'Formal writing avoids chatty words and uses vocabulary like "requested".'],
  [3, 'In "The children will study the animals.", what is the subject?', 'The children', ['the animals', 'will study', 'study'], 'The subject is the "do-er" and normally comes just before the verb.'],
  [3, 'In "Year 2 designed puppets.", what is the object?', 'puppets', ['Year 2', 'designed', 'There is no object'], 'The object comes straight after the verb and shows what the verb acts on.'],
  [3, 'In "Rula\'s mother went out.", what is the subject?', 'Rula\'s mother', ['out', 'went', 'went out'], 'The whole noun phrase "Rula\'s mother" is the subject: she did the going out.'],
  [3, 'In "My brother kicked the ball over the fence.", what is the object?', 'the ball', ['My brother', 'the fence', 'kicked'], '"The ball" comes straight after the verb and is what was kicked. "The fence" follows the preposition "over".'],
  [4, 'Which sentence is written in the passive voice?', 'The window was broken by me.', ['I broke the window.', 'I am breaking the window.', 'I will break the window.'], 'In a passive sentence the object becomes the subject, with "be" + past participle (was broken).'],
  [4, 'Which is the passive version of "Our dog ate it."?', 'It was eaten by our dog.', ['Our dog has eaten it.', 'Our dog was eating it.', 'It ate our dog.'], 'Passive: the object (it) becomes the subject, plus "was" + past participle (eaten).'],
  [4, 'Which sentence is in the active voice?', 'The school arranged a visit.', ['A visit was arranged by the school.', 'A visit was arranged.', 'A visit was being arranged.'], 'In an active sentence the subject does the action: the school arranged.'],
  [4, 'Which sentence uses a question tag, a feature of informal speech?', 'He\'s your friend, isn\'t he?', ['Is he your friend?', 'He is your friend.', 'Your friend is here.'], 'A question tag is a short question added to the end of a statement: "isn\'t he?".'],
  [4, 'Which adverbial shows a contrast between ideas?', 'On the other hand', ['As a consequence', 'Furthermore', 'Firstly'], '"On the other hand" and "in contrast" link paragraphs by showing a difference.'],
  [5, 'Which sentence uses the subjunctive form?', 'If I were you, I would apologise.', ['If I was you, I would apologise.', 'I was sure I would apologise.', 'I am going to apologise.'], '"If I were" is the subjunctive, used in formal writing.'],
  [5, 'Choose the verb for formal writing: "The school requires that all pupils ___ honest."', 'be', ['are', 'is', 'were'], 'After "requires that", formal English uses the subjunctive "be".'],
  [5, 'Which adverbial shows a result?', 'As a consequence', ['In contrast', 'On the other hand', 'However'], '"As a consequence" shows that one thing happened because of another.'],
  [5, 'Which sentence uses ellipsis (leaving out words that are expected)?', 'I wanted to help but I couldn\'t.', ['I wanted to help and I helped.', 'I helped my friend with her homework.', 'My friend helped me with my homework.'], 'The word "help" is left out after "couldn\'t" because the reader can predict it.'],
  [5, 'Which of these sentences is passive?', 'Our cat got run over by a bus.', ['He received a warning.', 'We had an accident.', 'A bus ran over our cat.'], '"Got run over" is passive: "get" + past participle. "Received" and "had" are just active past tense verbs.'],
];

/** Year 6 punctuation (English Appendix 2), plus Year 5 commas and parenthesis as warm-ups. */
const PUNCTUATION: Row[] = [
  [1, 'Which sentence means you are inviting Grandma to eat with you?', 'Let\'s eat, Grandma!', ['Let\'s eat Grandma!'], 'The comma separates the person being spoken to. Without it, Grandma is on the menu!'],
  [1, 'Which pair of punctuation marks can show parenthesis (extra information)?', 'Brackets', ['Full stops', 'Question marks', 'Apostrophes'], 'Brackets, dashes or commas can be used for parenthesis: My sister (who is 15) plays the drums.'],
  [1, 'Which sentence uses brackets correctly?', 'My sister (who is 15) plays the drums.', ['My sister (who is 15 plays) the drums.', '(My sister) who is 15 plays the drums.', 'My sister who (is 15 plays the drums.)'], 'The brackets go around the extra information only. The sentence still makes sense without it.'],
  [2, 'Which sentence describes a shark that eats people?', 'A man-eating shark swam past.', ['A man eating shark swam past.'], 'The hyphen joins "man-eating" into one describing word. Without it, it sounds like a man is eating a shark!'],
  [2, 'The sofa was worn out, so we had it ___.', 're-covered', ['recovered'], 'Re-cover (with a hyphen) means cover again. Recover means get better or get back.'],
  [2, 'What does a hyphen help to avoid?', 'Ambiguity (a sentence having two meanings)', ['Long sentences', 'Capital letters', 'Speech'], 'Hyphens join words so the meaning is clear, like "man-eating shark".'],
  [3, 'Which sentence uses a semi-colon correctly?', 'It\'s raining; I\'m fed up.', ['It\'s; raining I\'m fed up.', 'Because it\'s raining; I\'m fed up.', 'It\'s raining I\'m; fed up.'], 'A semi-colon joins two independent clauses (each could be a sentence on its own). "Because it\'s raining" is not independent.'],
  [3, 'Which punctuation mark could join these two independent clauses: "The film was long ___ I nearly fell asleep."?', 'A semi-colon', ['A comma', 'An apostrophe', 'A hyphen'], 'A semi-colon (or a dash, or a colon) can mark the boundary between independent clauses. A comma alone cannot.'],
  [3, 'Which sentence uses a dash to join two independent clauses?', 'The shop was closed – we went home.', ['The – shop was closed we went home.', 'The shop – was closed we went home.', 'The shop was closed we – went home.'], 'The dash goes at the boundary between the two clauses.'],
  [4, 'Which sentence uses a colon correctly?', 'You will need the following: a pencil, a ruler and a rubber.', ['You will: need a pencil, a ruler and a rubber.', 'You will need a pencil: a ruler and a rubber.', 'You: will need a pencil, a ruler and a rubber.'], 'A colon can introduce a list after a complete clause.'],
  [4, 'Which sentence uses a colon correctly between two clauses?', 'I knew what had happened: the dog had eaten my homework.', ['I knew: what had happened the dog had eaten my homework.', 'I knew what: had happened the dog had eaten my homework.', 'I knew what had happened the dog: had eaten my homework.'], 'The colon comes at the boundary between the clauses. The second clause explains the first.'],
  [4, 'What is a colon used for?', 'To introduce a list or an explanation', ['To show a question', 'To show possession', 'To end every sentence'], 'A colon (:) can introduce a list, or a clause that explains the first one.'],
  [5, 'Which sentence uses semi-colons correctly in a list?', 'We visited Paris, France; Rome, Italy; and Madrid, Spain.', ['We visited Paris; France, Rome; Italy, and Madrid; Spain.', 'We visited; Paris, France, Rome, Italy, and Madrid, Spain.', 'We visited Paris France; Rome Italy and; Madrid Spain.'], 'When list items already contain commas, semi-colons separate the items clearly.'],
  [5, 'Which punctuation mark introduces a list?', 'A colon', ['A semi-colon', 'A hyphen', 'An apostrophe'], 'A colon introduces a list. Semi-colons can separate items within a list.'],
  [5, 'Which sentence is punctuated correctly?', 'I love summer; the days are long and warm.', ['I love summer, the days are long and warm.', 'I love summer the days are long and warm.', 'I love; summer the days are long and warm.'], 'Two independent clauses need a semi-colon (or a full stop), not just a comma.'],
];

const BANKS: Record<string, () => Question[]> = {
  'spelling-words': spellingQuestions,
  'spelling-patterns': () => rowsToQuestions('spelling-patterns', PATTERNS, classifySpelling),
  homophones: () => rowsToQuestions('homophones', HOMOPHONES, (a, w) => `homophone:${[a.toLowerCase(), w.toLowerCase()].sort().join('/')}`),
  'grammar-y6': () => rowsToQuestions('grammar-y6', GRAMMAR, {
    'He received a warning.': 'gr-past-is-passive',
    'We had an accident.': 'gr-past-is-passive',
    'If I was you, I would apologise.': 'gr-subjunctive-was',
    'the fence': 'gr-object-preposition',
    'the animals': 'gr-subject-object-mixup',
    'My brother': 'gr-subject-object-mixup',
    'Year 2': 'gr-subject-object-mixup',
  }),
  'reading-y6': readingQuestions,
  'punctuation-y6': () => rowsToQuestions('punctuation-y6', PUNCTUATION, {
    'Because it\'s raining; I\'m fed up.': 'pu-semicolon-subordinate',
    'A comma': 'pu-comma-splice',
    'I love summer, the days are long and warm.': 'pu-comma-splice',
    'Let\'s eat Grandma!': 'pu-comma-meaning',
  }),
};

export function englishQuestions(skillId: string): Question[] {
  const bank = BANKS[skillId];
  if (!bank) throw new Error(`No English questions for ${skillId}`);
  return bank();
}

export function englishSkillIds(): string[] {
  return Object.keys(BANKS);
}

export function pickEnglishQuestion(
  skillId: string,
  level: Level,
  recentIds: string[],
  rng: () => number,
  prefer?: (q: Question) => boolean,
): Question {
  return pickFromBank(englishQuestions(skillId), level, recentIds, rng, prefer);
}
